### ISSUE TITLE
Create a history file during/after runs

### ISSUE THREAD

**Issue by parisholley** [browserstack/browserstack-runner#55] opened 2014-03-19 23:40 UTC
Create a JSON file that can be loaded in a subsequent run to allow the user to re-run failed tests (could implement in CLI similar to how VIM behaves when it detects a swap file).

**Comment by shirish87** [comment] 2016-01-27 06:57
@parisholley, while your dev use-case is valid, most devs are comfortable re-testing with all browsers just in case their changes cause a regression.

For (2) – BrowserStack worker timeouts, etc. should not be the reason for having a retry feature, imho. If these issues do ever occur, they will be fixed in the service.
Thanks.

**Closed by shirish87** 2016-01-27 06:57 UTC
