### ISSUE TITLE
mocha: tests run, but session times out

### ISSUE THREAD

**Issue by davidaurelio** [browserstack/browserstack-runner#94] opened 2014-09-22 09:01 UTC
I’m trying to run a mocha test suite with *browserstack-runner*, and the suite runs and passes (looking at the screenshots or in interactive sessions).

Nevertheless *browserstack-runner* does not pick up the results, and the session times out (message is “Timeout (Session timed out because the browser was idle for 300 seconds”).

My configuration file:

```json
{
    "username": "…",
    "key": "…",
    "test_framework": "mocha",
    "test_path": "test.html",
    "browsers": [
        "firefox_latest"
    ]
}
```

**Comment by forresto** [comment] 2015-01-08 16:20
Same issue for [the noflo-ui runner](https://github.com/noflo/noflo-ui/blob/master/spec/runner.html). In the [screenshot](https://s3.amazonaws.com/testautomation/8f2c21f9be64cc582ad7f3f1639644ba4fd604b9/js-screenshot-1420733875.png) I can see that all tests passed, but all systems time out.

**Comment by forresto** [comment] 2015-01-16 18:00
Anybody had any progress with this? Changing the browsers doesn't seem to help. I tested https://github.com/browserstack/url.js which does seem to work, with the same version of mocha and chai. The only obvious difference is that we're using Syn to simulate interaction, but that shouldn't make any difference with Mocha's reporting.

![screen shot 2015-01-16 at 12 58 47 pm](https://cloud.githubusercontent.com/assets/395307/5781322/a400f59e-9d7f-11e4-81f1-7450a148eb6b.png)

**Comment by algesten** [comment] 2015-01-22 14:20
I have the same problem. The test looks to be working when viewed interactively. But it just times out. sinon, chai, mocha.

**Comment by algesten** [comment] 2015-01-22 14:24
Think I cracked it. I moved all my script loading from <body> to the <head>, and suddenly it started working. I kept the run instruction in the body.

**Comment by jzaefferer** [comment] 2015-01-22 15:10
That sounds like something that was supposed to be fixed by https://github.com/browserstack/browserstack-runner/commit/4314a28524f23b672fb7e74aba74db9f0fa3e017 - any idea why its not working for mocha?

**Comment by algesten** [comment] 2015-01-23 06:00
Could it be that the tests have already run and your `mocha-plugin.js` [attaches event handlers](https://github.com/browserstack/browserstack-runner/blob/master/lib/_patch/mocha-plugin.js#L35) for events that have already fired?

**Comment by algesten** [comment] 2015-01-24 04:23
I'm pretty certain the event attach is the problem. Even after moving the scripts to the header, I would get intermittent errors. However it seems pretty solid once I did this:

    <script>window.onload = function() { mocha.run(); }</script>

**Comment by bgaillard** [comment] 2015-05-20 10:54
Hi, I also encounter the same problem, in my case : 
 * Calling `mocha.run()` after the window `load` event does not solve the problem ; 
 * https://github.com/browserstack/browserstack-runner/commit/4314a28524f23b672fb7e74aba74db9f0fa3e017 does not solve the problem either. 

I ended with a simple test, I encounter a timeout when the `test_path` property of my `browserstack.json` file references an HTML file under a sub-directory (its very strange). 

For example this works : 
```json
{
    "username": "xxxxxxxx",
    "key": "xxxxxxxx",
    "test_framework": "mocha",
    "test_path": "test.html",
    "timeout" : 30,
    "browsers": [
        {
            "browser": "chrome",
            "browser_version": "latest",
            "os": "OS X",
            "os_version": "Mountain Lion"
        }
    ]
}
```

This does not (the only change is the value of `test_path`) : 
```json
{
    "username": "xxxxxxxx",
    "key": "xxxxxxxx",
    "test_framework": "mocha",
    "test_path": "test/test.html",
    "timeout" : 30,
    "browsers": [
        {
            "browser": "chrome",
            "browser_version": "latest",
            "os": "OS X",
            "os_version": "Mountain Lion"
        }
    ]
}
```

The `test.html` file I used is very simple and contains no tests : 
```html
<!doctype html>
<html>
    <head>
        <link href="mocha.css" rel="stylesheet" />
        <script src="mocha.js"></script>
    </head>
    <body>
        <div id="mocha"></div>
        <script>
            mocha.setup('bdd');
            mocha.run();
        </script>
    </body>
</html>
```

But wait... It seems their is an other problem, if now I keep the `browserstack.json` file with a `test_path` equal to `test.html` and if I move the file `mocha.js` into a parent directory I also encounter a timeout. 

For example, I have the following files : 
```
js
   - mocha.js
tests 
  - browserstack.json
  - test.html
```

The path to `mocha.js` is slighlty modified in the `test.html` file : 
```html
<script src="../js/mocha.js"></script>
```

Then if I run the tests under the `tests` directory I also encounter a timeout. 

So it seems their are 2 different problems (both are related to directory structure, I did'nt execute those tests with Jasmine or an other unit test tool but perhaps those bugs are also encountered with other tools...) : 
 * The `test_path` property does not support files under sub-directories ; 
 * Path referenced in the `test_path` file must be placed in a sub-directory of the directory where the `browserstack.json` file is placed.

**Comment by cutandpastey** [comment] 2015-09-02 13:41
@bgaillard I think your issue is a different bug. I can confirm however that I had the a bunch of mocha tests that timed out using the default mocha set-up: http://mochajs.org/#running-mocha-in-the-browser 




> I'm pretty certain the event attach is the problem. Even after moving the scripts to the header, I would get intermittent errors. However it seems pretty solid once I did this:
> 
> <script>window.onload = function() { mocha.run(); }</script>

using the above fixed everything! Thanks @algesten

**Comment by GGAlanSmithee** [comment] 2015-12-01 11:52
Had the same issue, and the fix suggested by @algesten work fine - thanks!

To clarify for anyone finding this issue, for this to work, you have to link to mocha (and related libs like chai) in the header, and then call `mocha.run()` in `window.onload`.

** Example

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Mocha</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="mocha.css" />
    
    <script src="chai.js"></script>
    <script src="mocha.js"></script>
  </head>
  <body>
    <div id="mocha"></div>
    
    <script>mocha.setup('bdd');</script>
    <script src="tests.js"></script>
    <script>
      window.onload = function() {
        mocha.run();
      };
    </script>
  </body>
</html>
```

**browserstack.json**
```json
{
  "username" : <username>,
  "key" : <key>,
  "test_framework": "mocha",
  "test_path": "index.html",
  "timeout": 30,
  "browsers": [
    {
      "browser": "ie",
      "browser_version": "10.0",
      "device": null,
      "os": "Windows",
      "os_version": "8"
    }
  ]
}
```

**tests.js**
```js
var expect = chai.expect;

describe('test', function() {
    it('passes', function() {
        expect(10 === 10).to.be.true;
    });
    
    it('fails', function() {
        expect(10 === "10").to.be.false;
    });
})
```

**Comment by luca-poddigue** [comment] 2015-12-13 17:30
@bgaillard Had the same issue on *Jasmine*. Don't know how come it can be possible but it works fine to me. Thanks for the contribution, I could have searched for years.

**Comment by HiAaronCody** [comment] 2016-01-21 06:27
@luca-poddigue, how did you delay the start of Jasmine?

**Comment by luca-poddigue** [comment] 2016-01-21 12:33
@HiAaronCody It was not a matter of delay. It just run out of time. It's been quite a long time since I had this issue, but if I remember properly, it was due to the fact that the html file containing the Jasmine spec runner was in a subdirectory of the main dir. Simply moving it to the root did the trick for some reason. A similar issue was mentioned by @bgaillard in a comment above.

**Comment by shirish87** [comment] 2016-01-29 14:43
In case you absolutely need to have `browserstack.json` in a subfolder (such as `tests`), you can set the `BROWSERSTACK_JSON` environment variable to point to the location of `browserstack.json`.

I have set up two sample repos with [mocha](https://github.com/shirish87/browserstack-runner-mocha-adv) and [jasmine](https://github.com/shirish87/browserstack-runner-jasmine-adv).

Let me know if you need any help.

**Comment by shirish87** [comment] 2016-02-04 07:04
Closing this since @algesten's suggestion of moving `mocha.run()` to `window.onload` works, and the rest is more of a folder structure organization issue. We'll create a Wiki page to explain this better.

We'll soon have better verbose logging (#146) that will help debug times when the server has failed to serve framework patch files or any other static files.

Please reopen if you feel there's an issue with runner.

**Closed by shirish87** 2016-02-04 07:04 UTC

**Comment by soulmerge** [comment] 2016-05-11 09:12
I have the same problem and do not think this is an issue with mocha or the assertion library. The problem exists even when running the test application in https://github.com/browserstack/browserstack-runner-sample

**Comment by soulmerge** [comment] 2016-05-11 10:12
I just noticed that it seems to be running for exactly 1 minute. I suppose this is the minimum time allocated to a browser instance, but could not find any documentation to back this up. Or is it really a bug?

**Comment by shirish87** [comment] 2016-05-11 16:16
@soulmerge, could you please confirm if:
* Tests appear to run correctly in the browser on BrowserStack.[Automate Dashboard](https://www.browserstack.com/automate).
* You receive test run summary in the console such as `[OS X Lion, Chrome 49.0] Passed: 3 tests, 3 passed, 0 failed; ran for 444ms`

If its about browserstack-runner not exiting after all tests have run (as experienced when running the QUnit sample), we're [fixing it](https://github.com/browserstack/browserstack-runner/pull/156).

**Comment by mnichols** [comment] 2017-08-24 05:42
I just hit this issue with being particular about where `script` tags are found in the document (thanks @algesten and @GGAlanSmithee ) using mocha 2.5.2 (I think mocha 3 is still not supported). 

I get `NaN` for mocha counts of failures and tests run on many browsers or devices tho, eg
```
[ios 8.3, iPhone 6] Passed: 38 tests, NaN passed, NaN failed, NaN skipped; ran for NaNms
All tests done, failures: NaN.
```

**Comment by vedharish** [comment] 2017-08-24 06:58
@mnichols Yes, we have an open issue #185  for mocha 3
