### ISSUE TITLE
IE8 has console error

### ISSUE THREAD

**Issue by sdaikichi** [browserstack/browserstack-runner#161] opened 2016-07-25 08:20 UTC
I running multi-browser Javascript tests which catch console messages.
Only IE 8(and older) has Console Error:"'prototype' is null or not an object"

(Screenshots with BrowserStack Live)
![image](https://cloud.githubusercontent.com/assets/12888409/17094660/bdc29542-528b-11e6-8a45-7044222fd9dc.png)

Probably it comes from JSON3
https://github.com/bestiejs/json3/issues/86

**Comment by jzaefferer** [comment] 2016-07-25 10:46
@flore77 this might've been introduced by #159, can you check that?

**Comment by flore77** [comment] 2016-07-25 11:37
Yes, I will check.

**Comment by flore77** [comment] 2016-07-25 19:34
@sdaikichi from where have you installed  `browserstack-runner`? `npm`? or here from `github`?

@jzaefferer if he got it from npm, then it is definitely not from #159, because they didn't make a new release after merging.

**Comment by sdaikichi** [comment] 2016-07-26 05:05
@flore77 I installed from npm.

**Comment by vedharish** [comment] 2016-07-26 07:31
The console error is from [browserstack-util.js](https://github.com/browserstack/browserstack-runner/blob/4306e4d088fbb3502baf4243a739f95a0b906f93/lib/_patch/browserstack-util.js) and is present in the already released version.

**Comment by jzaefferer** [comment] 2016-07-26 09:41
@tr4n2uil could you look into that? Seems like a recent regression

**Comment by vedharish** [comment] 2016-07-27 09:57
@sdaikichi Can you please confirm the test framework that you are using? If you are using `qunit`, you need to include `qunit.js` in your html files. [Also `qunit >= 2.0.0` does not support IE8](https://github.com/jquery/qunit/issues/1012)

**Comment by sdaikichi** [comment] 2016-07-27 11:49
@vedharish Im using mocha.

**Comment by jzaefferer** [comment] 2016-07-27 19:28
Its not documented anywhere and accordingly hard to tell, but I think Mocha supports IE8: https://github.com/mochajs/mocha/blob/master/karma.conf.js#L91

**Comment by tr4n2uil** [comment] 2016-08-04 19:40
@sdaikichi Are you still facing this issue ?

**Comment by sdaikichi** [comment] 2016-08-05 06:05
@tr4n2uil yes.

**Comment by oliverfriedmann** [comment] 2016-11-16 04:08
The issue seems to be that Webpack injects an empty exports = {} as a "root" object into JSON3, but JSON3 sort-of requires the global window object as a root on IE <= 8.

**Comment by mohitmun** [comment] 2018-03-09 08:40
As mentioned by @oliverfriedmann, JSON3 requires the global window object as a root, but here issue is not with webpack, but with [following condition](https://github.com/bestiejs/json3/blob/v3.3.0/lib/json3.js#L11) in json3
```  
var freeGlobal = typeof global == "object" && global;
if (freeGlobal && (freeGlobal["global"] === freeGlobal || freeGlobal["window"] === freeGlobal)) {
  root = freeGlobal;
}
```

apart from IE8, other browsers evaluates `window.window === window` as `true`, but IE8 evaluates to `false`. it doesn't enter `if` condition and `window` is not assigned to `root`. 
Checkout [this](https://stackoverflow.com/questions/4180013/javascript-this-window-not-equal-to-window#comment4516668_4180013) comment.

**Comment by carhartl** [comment] 2018-04-13 20:07
> The console error is from browserstack-util.js and is present in the already released version

> The issue seems to be that Webpack injects an empty exports = {} as a "root" object

I'm seeing said `exports:{}` in https://github.com/browserstack/browserstack-runner/blob/4306e4d088fbb3502baf4243a739f95a0b906f93/lib/_patch/browserstack-util.js#L1 - is that the issue? We're getting this error here while trying to setup BrowserStack w/ browserstack-runner for the js-cookie project..

**Comment by carhartl** [comment] 2019-01-03 10:00
I‘m running out of ideas.. is there any way to workaround this? We aimed to but can‘t run automated tests in IE 6-8 due to this.

The question whether we _should_ still be testing in these browsers is another one :)

**Closed** 2021-04-21 10:24 UTC
