### ISSUE TITLE
Sample Node.js test not working

### ISSUE THREAD

**Issue by trusktr** [browserstack/browserstack-runner#187] opened 2017-09-01 00:45 UTC
When I rune the Node.js sample test from the Automate website, I get an error like this:

```
/usr/local/lib/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

WebDriverError: unknown error: Element <input value="I'm Feeling Lucky" aria-label="I'm Feeling Lucky" id="gbqfbb" name="btnI" type="submit"> is not clickable at point (556, 411). Other element would receive the click: <div class="sbqs_c"
```

**Comment by mohitmun** [comment] 2018-03-07 08:20
Hey @trusktr, 
Please report any issues regarding node.js sample [here](https://github.com/browserstack/automate-node-samples/). it has nothing to do with browserstack-runner.

Thanks

**Comment by sinstein** [comment] 2018-03-08 07:24
Duplicate of #186

**Closed by sinstein** 2018-03-08 07:24 UTC
