### ISSUE TITLE
Incomplete reload-blank-page solution

### ISSUE THREAD

**Issue by jzaefferer** [browserstack/browserstack-runner#131] opened 2015-08-14 18:10 UTC
This was posted by @sanox on #123, I'm copying it in here to make sure it doesn't get lost on a closed PR. Hoping for @shirish87 to take a look.

---

After some digging I have found out that this pull request does not fix the blank page issue.
The reason for that is because of the following things:
- 1. The worker acknowledge-state is not good enough to listen for, because it is not handle correct, sometimes you get "Received ack" before even the browser is launched. And when that happens and the page fails to load correct, the page won't reload again, because it check if the worker.isAckd is false before the reload. See ackTimeout function below:

``` javascript
 this.ackTimeout = setTimeout(function () {
      if (self.isAckd) { // Then if the page fails to load, this expression is getting true and then it return. And nothing else will happen
        // Already ack'd
        return;
      }

      // worker has not acknowledged itself in 60 sec, reopen url
      client.changeUrl(self.id, { url: self.buildUrl() }, function () {
        logger.debug("[%s] Sent Request to reload url", self.getTestBrowserInfo());
      });

    }, ackTimeout * 1000);
```

Example in the log: 

[OS X Yosemite, Safari 8.0] Received ack
[OS X Yosemite, Safari 8.0] Launched
[OS X Yosemite, Safari 8.0] Awaiting ack
- 2. When trying to reload the page, it does not include the worker_key data and therefore showing "404 Not found" when trying to reload.

Example: 

00:01 - Open url http://localhost:8888/test.html?_worker_key=1539fd49-2783-4e91-8cfd-e192afec9f2c&_browser_string=OS%20X%20Yosemite%2C%20Safari%208.0 
01:08 - Open url http://localhost:8888/test.html?_worker_key=&_browser_string=OS%20X%20Yosemite%2C%20Safari%208.0
- 3. The function testActivityTimeout (in cli.js) will never execute anymore, because the property "acknowledged" on the worker object is never set to true. Instead another boolean is used to indicate if worker is acknowledge called isAckd. But that is not updated everywhere in the code.

I have done a temporary fix local, where I in the function "testActivityTimeout" try to reload the page 1 time if the test is not completed within the specified timeout.
It works and no more session timeout is visible.

Another solution I tried that worked was to listen if any request was made to "_/report" within the specified timeout, and if not reload the page, that also works.

Let me know if you have any questions.

**Comment by shirish87** [comment] 2015-08-14 21:51
@sanox, could you please elaborate on this:
> sometimes you get "Received ack" before even the browser is launched

This should never happen. Only the remote browser calls the test URL, and once that request is received, the worker is marked as ack'd.

Thanks.

**Comment by Sanox** [comment] 2015-08-17 09:02
The "Received ack" is logged and the boolean worker.isAckd is set when the browser request the test URL, but that is even before the server send the response.
Below is a example from the log when I run in verbose mode when that is happening:

[Windows 7, Internet Explorer 11.0] Launching
[Windows 7, Internet Explorer 11.0] Received ack
[Windows 7, Internet Explorer 11.0] Launched

[OS X Mountain Lion, Safari 6.1] Launching
[OS X Mountain Lion, Safari 6.1] Received ack
[OS X Mountain Lion, Safari 6.1] Launched

Of course the log may get like that because of the poller interval in the "statusPoller"-object in cli.js. 
But still, it set worker.isAckd even before the server send the response of the test URL.
Not sure if that is what we want?

I think the acknowledge-state is a bad thing to look for when we want to see if the page is loaded correct.
The reason for that is because how the state is handle and that it makes no guarantee that the page is loaded by the browser.
And that is why the awaitAck-function is not working correct, because it just check the acknowledge-state.

**Comment by shirish87** [comment] 2015-08-17 18:19
Thanks for looking into this, @Sanox.
So, the retry fix specifically addresses a possible issue around the browser never opening the test URL. With this fix and the existing activity timeouts in place, there should be some degree of certainty that the test URL will be opened in the remote browser (or fail).

You're right - this fix doesn't guarantee that the page was successfully loaded by the browser. If we experience cases in which that does happen despite this fix, we would be looking into it.

"Received ack" being logged before "Launched" seems to be a log order/poll interval thing. While testing, I added a `console.log(request.headers['user-agent'])` [here](https://github.com/shirish87/browserstack-runner/blob/retry_fix/lib/server.js#L31) to ensure the URL was only being accesses by the remote browser.

**Comment by Sanox** [comment] 2015-08-18 14:41
The problem is that the fixes for the blank screen page that is merge don't work.
The reason for that is that it only checks the acknowledge-state to decide wether to reload or not.
You will always receive acknowledge-state, and there is the problem. So if we only check that, it won't help.

I have created a pull-request, https://github.com/browserstack/browserstack-runner/pull/134 that is not looking for the acknowledge-state because it is not what we want.
It works good for me, no more blank page issues. Feel free to merge if you want, or make changes in your own version if you would like that instead.

**Comment by shirish87** [comment] 2015-08-18 20:24
I guess part of the problem is being able to reproduce this issue consistently. Sounds like you're able to reproduce this even with the existing fixes, so I'll keep this issue open for further feedback. 

Hope you understand that it's a little hard to imagine why the remote browser would request for a page (and hence worker is marked as "ackd") but not load it successfully from that point on.
Your fix of reloading the URL on activity timeout would certainly be needed if that is indeed happening. Thanks for the PR! : )

**Comment by Sanox** [comment] 2015-08-19 06:58
I understand it's hard to imagine that, but I always receive acknowledge-state, even if the browser cannot load the page. That's why I keep talking about it :)

I have easy to reproduce it, maybe because my setup is little different then yours?
I run my tests in 10 different browsers, on Mac OS and Windows, all at once.

**Comment by TehShrike** [comment] 2015-09-05 17:34
I ran into this when setting up testing for [abstract-state-router](https://github.com/TehShrike/abstract-state-router).

In my own reproduction, the key seems to be how large the JS file is.

I build my JavaScript file with browserify using the `-d` flag to add source maps, the resulting JS file is 963282 bytes.  Whenever I attempt to test the file, I get this log:

```
Launching server on port: 8888
[Sat Sep 05 2015 12:28:22 GMT-0500 (CDT)] Launching tunnel
[Sat Sep 05 2015 12:28:25 GMT-0500 (CDT)] Tunnel launched
Launching 6 worker(s) for 6 run(s).
[Windows 8.1, Chrome 45.0] Launching
[Windows XP, Firefox 40.0] Launching
[OS X El Capitan, Safari 9.0] Launching
[Windows 7, Chrome 45.0] Launching
[Windows 7, Internet Explorer 10.0] Launching
[Windows 8.1, Internet Explorer 11.0] Launching
[Windows XP, Firefox 40.0] Launched
[Windows XP, Firefox 40.0] Awaiting ack
[Windows XP, Firefox 40.0] Received ack
```

After that "Received ack", nothing ever happens.

If I build without source maps, the JS file is 366544 bytes, and the tests run fine every time.

I can reproduce this whether I am testing against one browser, or many, running locally on OS X.

**Comment by mohitmun** [comment] 2018-03-15 13:45
@nording Are you still facing this issue?

**Comment by nording** [comment] 2018-03-16 14:12
@mohitmun We changed our setup a bit and are now using Browserstack together with Karma, we don't  see this issue using that setup.

**Comment by mohitmun** [comment] 2018-03-26 06:50
Cannot replicate same issue. closing, reopen with more details if issue persist.

**Closed by mohitmun** 2018-03-26 06:50 UTC
